### ISSUE TITLE
Trigger points

### ISSUE THREAD

**Issue by pettrs** [mlgudi/rl-plugins#5]
I'm not a videomaker, but i'd still love to put this plugin to use somewhere. Would it be possible to add triggerpoints for different sequences? I'd love to be able to have a camera movement when I cross in through the GE gates, enter a boss lair, etc... the trigger points could be stepping on a certain tile, doing an animation, afk timer etc...

I would for example, if I've been afk for more than 1 minute, have my camera start spectating my character in cool ways

https://github.com/mlgudi/rl-plugins/assets/75093127/c2942ca5-b2e0-457d-b36b-b7cc350412a6

**Comment by mlgudi** [comment]
Hey! Thanks for the suggestions. I had the very same idea myself, but I think - at least in the case of location sequences/triggers - it would not be wise due the inability to interact with many things whilst in detached camera mode.

As for the AFK camera, I love the concept. It is reminiscent of the 2008-era login screen (I think OSHD just introduced this). However, I don't think it necessarily fits the aims of this plugin. I'm sure it would get a lot of love as a standalone plugin.

I'm going to close this for now and take a look at your other issues.
